version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tienda_videojuegos  
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: tienda_videojuegos
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql  # Persistir los datos de la base de datos
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
